package plugindatamodel

/* out of date as of 6/21/2022
The main elements of concern in a plugin are the following elements:
1. A Manifest Definition File
2. A Manifest file
3. A Payload File

## Manifest Definition
	Responsible for describing the possible inputs and outputs that a plugin container can work with
	- describes optional and required inputs and outputs
	- is supplied with a registerd plugin
	- does not change model for model. ?is this still true?
## Manifest File
	Specific to a model, describes the specific inputs and outputs for a model based on the manifest definition
	- describes selected inputs and outputs
	- is defined by an MCAT and mutated by a user to reflect sources for specific inputs
	- changes model for model
## Payload file
	Specific to a model and event
	- describes where inputs can be found and where to put outputs
	- is generated by wat
	- changes event by event for a given model
*/
