package plugindatamodel

/* up to date as of 6/21/2022
The main elements of concern in a plugin are the following elements:
1. A Manifest File
2. A Linked Manifest file
3. A Payload File

## Manifest
	Responsible for describing the inputs and outputs specific to a model and a plugin
	- describes inputs and outputs
	- is generated by an MCAT based on a model for a specific plugin.
	- is unique to a model and plugin combination.
## Linked Manifest File
	Specific to a model and plugin, describes the specific inputs (and what manifest will be generating the input) and outputs for a model based on the manifest definition
	- describes selected inputs and what manifest will be generating the input and outputs
	- is defined by a user to reflect sources for specific inputs
	- changes based on a model, and the overal wat job it is designed to be linked in.
## Payload file
	Specific to a plugin, model, and event
	- describes where inputs can be found and where to put outputs
	- is generated by wat
	- changes event by event for a given model
*/
